# Cross-platform user-space device driver layer Linux kernel Kbuild file
#
# See https://www.kernel.org/doc/html/latest/kbuild/modules.html

obj-m := cuddl.o
cuddl-y := src/cuddlk_linux.o ../src/cuddlk_common.o

obj-m += cuddl_manager.o
cuddl_manager-y := src/cuddlk_manager_linux.o ../src/cuddlk_manager_common.o

obj-m += cuddl_janitor.o
cuddl_janitor-y := src/cuddlk_janitor_linux.o

ccflags-y := -I$(src)/include \
             -I$(src)/../include \
             -I$(src)/../../common/include \
             -DCUDDLKI_COMMIT_HASH=\"`git -C $(src) rev-parse HEAD`\" \
             -DCUDDLKI_REPO_IS_DIRTY=`git -C $(src) diff --quiet HEAD && echo 0 || echo 1`
